# Generated by Django 5.2.5 on 2025-09-03 11:31

import hlsfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('video', hlsfield.fields.AdaptiveVideoField(dash_manifest_field='dash_manifest', hls_playlist_field='hls_master', upload_to='adaptive_videos/', verbose_name='Адаптивное видео')),
                ('hls_master', models.CharField(blank=True, max_length=500, null=True, verbose_name='HLS плейлист')),
                ('dash_manifest', models.CharField(blank=True, max_length=500, null=True, verbose_name='DASH манифест')),
            ],
            options={
                'verbose_name': 'Адаптивное видео',
                'verbose_name_plural': 'Адаптивные видео',
            },
        ),
        migrations.CreateModel(
            name='DASHVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('video', hlsfield.fields.DASHVideoField(dash_manifest_field='dash_manifest', upload_to='dash_videos/', verbose_name='DASH видео')),
                ('dash_manifest', models.CharField(blank=True, max_length=500, null=True, verbose_name='DASH манифест')),
            ],
            options={
                'verbose_name': 'DASH видео',
                'verbose_name_plural': 'DASH видео',
            },
        ),
        migrations.CreateModel(
            name='HLSVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('video', hlsfield.fields.HLSVideoField(hls_playlist_field='hls_master', upload_to='hls_videos/', verbose_name='HLS видео')),
                ('hls_master', models.CharField(blank=True, max_length=500, null=True, verbose_name='HLS плейлист')),
            ],
            options={
                'verbose_name': 'HLS видео',
                'verbose_name_plural': 'HLS видео',
            },
        ),
        migrations.CreateModel(
            name='SimpleVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('video', hlsfield.fields.VideoField(duration_field='duration', height_field='height', preview_field='preview', upload_to='simple_videos/', verbose_name='Видеофайл', width_field='width')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Длительность')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Превью')),
            ],
            options={
                'verbose_name': 'Простое видео',
                'verbose_name_plural': 'Простые видео',
            },
        ),
    ]
