# Конфигурация для pip-audit

[tool.pip-audit]
# Исключаем локальные/dev пакеты
ignore-packages = [
    "django-hlsfield"  # Локальный dev пакет, не на PyPI
]


# Форматы вывода
format = "table"
output = "pip-audit-results.json"

# Дополнительные настройки
desc = true           # Показывать описание уязвимостей
summary = true        # Показывать итоговую сводку
