name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string
      prerelease:
        description: 'Is this a prerelease?'
        required: false
        type: boolean
        default: false

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install bump2version
        pip install -e .

    - name: Update version
      run: |
        bump2version --new-version ${{ github.event.inputs.version }} patch
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Bump version to ${{ github.event.inputs.version }}"
        git tag v${{ github.event.inputs.version }}

    - name: Push changes
      run: |
        git push origin main
        git push origin v${{ github.event.inputs.version }}

    - name: Generate changelog
      id: changelog
      run: |
        echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        git log --pretty=format:"* %s" $(git describe --tags --abbrev=0 HEAD~1)..HEAD >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.version }}
        release_name: Release v${{ github.event.inputs.version }}
        body: |
          ## Changes in v${{ github.event.inputs.version }}

          ${{ steps.changelog.outputs.CHANGELOG }}

          ## Installation

          ```bash
          pip install django-hlsfield==${{ github.event.inputs.version }}
          ```

          ## What's Changed
          * Full changelog: https://github.com/${{ github.repository }}/compare/v${{ github.event.inputs.version }}...main
        draft: false
        prerelease: ${{ github.event.inputs.prerelease }}
